-- MySQL Script generated by MySQL Workbench
-- Sun 17 Apr 2016 02:52:55 PM COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estetica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estetica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estetica` DEFAULT CHARACTER SET utf8 ;
USE `estetica` ;

-- -----------------------------------------------------
-- Table `estetica`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Cliente` (
  `Cli_cc` INT NOT NULL COMMENT '		',
  `Cli_nombre` VARCHAR(15) NOT NULL,
  `Cli_apellido` VARCHAR(15) NOT NULL,
  `Cli_telefono` INT NULL,
  `Cli_dieccion` VARCHAR(20) NULL,
  PRIMARY KEY (`Cli_cc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Tipo horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Tipo horario` (
  `Tip_id` INT NOT NULL,
  `Tip_descripcion` VARCHAR(45) NULL,
  `Tip_hora_inicio` INT NULL,
  `Tip_hora fin` INT NULL,
  PRIMARY KEY (`Tip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Horario` (
  `Hor_id` INT NOT NULL AUTO_INCREMENT,
  `Hor_lunes` INT NOT NULL,
  `Hor_martes` INT NOT NULL,
  `Hor_miercoles` INT NOT NULL,
  `Hor_jueves` INT NOT NULL,
  `Hor_viernes` INT NOT NULL,
  `Hor_sabado` INT NOT NULL,
  `Hor_domingo` INT NOT NULL,
  `Horariocol` INT NOT NULL,
  PRIMARY KEY (`Hor_id`),
  INDEX `algo _idx` (`Hor_lunes` ASC),
  INDEX `fk_martes_idx` (`Hor_martes` ASC),
  INDEX `fk_miercoles_idx` (`Hor_miercoles` ASC),
  INDEX `fk_jueves_idx` (`Hor_jueves` ASC),
  INDEX `fk_viernes_idx` (`Hor_viernes` ASC),
  INDEX `fk_sabado_idx` (`Hor_sabado` ASC),
  INDEX `fk_domingo_idx` (`Hor_domingo` ASC),
  CONSTRAINT `fk_lunes`
    FOREIGN KEY (`Hor_lunes`)
    REFERENCES `estetica`.`Tipo horario` (`Tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_martes`
    FOREIGN KEY (`Hor_martes`)
    REFERENCES `estetica`.`Tipo horario` (`Tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_miercoles`
    FOREIGN KEY (`Hor_miercoles`)
    REFERENCES `estetica`.`Tipo horario` (`Tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jueves`
    FOREIGN KEY (`Hor_jueves`)
    REFERENCES `estetica`.`Tipo horario` (`Tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viernes`
    FOREIGN KEY (`Hor_viernes`)
    REFERENCES `estetica`.`Tipo horario` (`Tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sabado`
    FOREIGN KEY (`Hor_sabado`)
    REFERENCES `estetica`.`Tipo horario` (`Tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_domingo`
    FOREIGN KEY (`Hor_domingo`)
    REFERENCES `estetica`.`Tipo horario` (`Tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Empleado` (
  `Emp_cc` INT NOT NULL COMMENT '	',
  `Emp_nombre` VARCHAR(40) NOT NULL,
  `Emp_Apellido` VARCHAR(40) NOT NULL,
  `Emp_telefono` INT NULL,
  `Emp_direccion` VARCHAR(40) NULL,
  `Cargo_id` int NOT NULL,
  `Horario_Hor_id` INT NOT NULL,
  PRIMARY KEY (`Emp_cc`),
  INDEX `fk_empleado_Horario1_idx` (`Horario_Hor_id` ASC),
  CONSTRAINT `fk_empleado_Horario1`
    FOREIGN KEY (`Horario_Hor_id`)
    REFERENCES `estetica`.`Horario` (`Hor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `fk_Empleado_Cargo_idx` (`Cargo_id` ASC),
  CONSTRAINT `fk_empleado_Cargo1`
    FOREIGN KEY (`Cargo_id`)
    REFERENCES `estetica`.`Cargo` (`Cargo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Venta` (
  `Ven_id` INT NOT NULL,
  `Ven_costo` DOUBLE NULL,
  `Ven_fecha` DATE NOT NULL,
  `Cli_cc` INT NOT NULL,
  `Ven_Emp_cc` INT NOT NULL,
  PRIMARY KEY (`Ven_id`),
  INDEX `fk_Venta_Emp_idx` (`ven_Emp_cc` ASC),
  INDEX `fk_Ven_Cli_idx` (`Cli_cc` ASC),
  CONSTRAINT `fk_Ven_Cli`
    FOREIGN KEY (`Cli_cc`)
    REFERENCES `estetica`.`Cliente` (`Cli_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Emp`
    FOREIGN KEY (`Ven_Emp_cc`)
    REFERENCES `estetica`.`Empleado` (`Emp_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Venta Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Venta_Producto` (
  `Ven_id` INT NOT NULL,
  `Venp_id` INT NOT NULL,
  PRIMARY KEY (`Venp_id`),
  CONSTRAINT `fk_VenPro_Vent`
    FOREIGN KEY (`Ven_id`)
    REFERENCES `estetica`.`Venta` (`Ven_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Producto` (
  `Pro_id` INT NOT NULL,
  `Pro_nombre` VARCHAR(20) NULL,
  `Pro_uso` VARCHAR(100) NULL,
  `sto_id` INT NULL,
  PRIMARY KEY (`Pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Proveedor` (
  `Prov_id` INT NOT NULL COMMENT '	',
  `Prov_nombre` VARCHAR(25) NULL,
  `Prov_tipo` VARCHAR(15) NULL,
  `Prov_telefono` INT NULL,
  PRIMARY KEY (`Prov_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Protocolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Protocolo` (
  `Proto_id` INT NOT NULL,
  `Proto_materiales` VARCHAR(145) NULL,
  `Proto_ubicacion` VARCHAR(45) NULL,
  `Proto_medidas` VARCHAR(145) NULL,
  `Proto_recomend` VARCHAR(145) NULL,
  PRIMARY KEY (`Proto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`tipoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`tipoServicio` (
  `idtipoServicio` INT NOT NULL AUTO_INCREMENT,
  `tServ_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Servicio` (
  `Ser_id` INT NOT NULL,
  `Ser_nombre` VARCHAR(25) NULL,
  `Ser_numsesiones` INT NULL,
  `Proto_id` INT NOT NULL,
  `tipoServicio_idtipoServicio` INT NOT NULL,
  PRIMARY KEY (`Ser_id`),
  INDEX `fk_TSer_Proto_idx` (`Proto_id` ASC),
  INDEX `fk_Servicio_tipoServicio1_idx` (`tipoServicio_idtipoServicio` ASC),
  CONSTRAINT `fk_TSer_Proto`
    FOREIGN KEY (`Proto_id`)
    REFERENCES `estetica`.`Protocolo` (`Proto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicio_tipoServicio1`
    FOREIGN KEY (`tipoServicio_idtipoServicio`)
    REFERENCES `estetica`.`tipoServicio` (`idtipoServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Venta Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Venta_Servicio` (
  `Ven_id` INT NOT NULL,
  `Ser_id` INT NOT NULL,
  `VenS_id` INT NOT NULL,
  INDEX `fk_VenSer_Ser_idx` (`Ser_id` ASC),
  PRIMARY KEY (`VenS_id`),
  CONSTRAINT `fk_VenSer_Vent`
    FOREIGN KEY (`Ven_id`)
    REFERENCES `estetica`.`Venta` (`Ven_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VenSer_TSer`
    FOREIGN KEY (`Ser_id`)
    REFERENCES `estetica`.`Servicio` (`Ser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Sesion` (
  `Ses_id` INT NOT NULL,
  `Ses_Fecha` DATE NOT NULL,
  `Ses_avance` VARCHAR(100) NOT NULL,
  `Ses_Emp_cc` INT NOT NULL,
  `Ses_comentario` VARCHAR(500) NULL,
  `Venta_Servicio_Vens_id` INT NOT NULL,
  PRIMARY KEY (`Ses_id`),
  INDEX `fk_Ses_Emp_idx` (`Ses_Emp_cc` ASC),
  INDEX `fk_Sesion_Venta_Servicio1_idx` (`Venta_Servicio_VenS_id` ASC),
  CONSTRAINT `fk_Ses_Emp`
    FOREIGN KEY (`Ses_Emp_cc`)
    REFERENCES `estetica`.`Empleado` (`Emp_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sesion_Venta_ServicioSesionServicio1`
    FOREIGN KEY (`Venta_Servicio_Vens_id`)
    REFERENCES `estetica`.`Venta_Servicio` (`Vens_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`CompraProveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`CompraProveedor` (
  `idCompraProveedor` INT NOT NULL,
  `CPRO_costo` DOUBLE NULL,
  `Proveedor_Prov_id` INT NOT NULL,
  PRIMARY KEY (`idCompraProveedor`),
  INDEX `fk_CompraProveedor_Proveedor1_idx` (`Proveedor_Prov_id` ASC),
  CONSTRAINT `fk_CompraProveedor_Proveedor1`
    FOREIGN KEY (`Proveedor_Prov_id`)
    REFERENCES `estetica`.`Proveedor` (`Prov_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Adquisicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Adquisicion` (
  `idAdquisicion` INT NOT NULL AUTO_INCREMENT,
  `Producto_Pro_id` INT NOT NULL,
  `CompraProveedor_idCompraProveedor` INT NOT NULL,
  `adq_preciocompra` INT NOT NULL,
  `Fecha_Vencimiento` DATE NULL,
  PRIMARY KEY (`idAdquisicion`),
  INDEX `fk_Adquisicion_Producto1_idx` (`Producto_Pro_id` ASC),
  INDEX `fk_Adquisicion_CompraProveedor1_idx` (`CompraProveedor_idCompraProveedor` ASC),
  CONSTRAINT `fk_Adquisicion_Producto1`
    FOREIGN KEY (`Producto_Pro_id`)
    REFERENCES `estetica`.`Producto` (`Pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Adquisicion_CompraProveedor1`
    FOREIGN KEY (`CompraProveedor_idCompraProveedor`)
    REFERENCES `estetica`.`CompraProveedor` (`idCompraProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(45) NULL,
  `Disponible` INT NULL,
  `Sesion_Ses_id` INT NULL,
  `Adquisicion_idAdquisicion` INT NOT NULL,
  `Venta_Producto_Venp_id` INT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_Inventario_Sesion1_idx` (`Sesion_Ses_id` ASC),
  INDEX `fk_Inventario_Adquisicion1_idx` (`Adquisicion_idAdquisicion` ASC),
  INDEX `fk_Inventario_Venta_Producto1_idx` (`Venta_Producto_Venp_id` ASC),
  CONSTRAINT `fk_Inventario_Sesion1`
    FOREIGN KEY (`Sesion_Ses_id`)
    REFERENCES `estetica`.`Sesion` (`Ses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Adquisicion1`
    FOREIGN KEY (`Adquisicion_idAdquisicion`)
    REFERENCES `estetica`.`Adquisicion` (`idAdquisicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Venta_Producto1`
    FOREIGN KEY (`Venta_Producto_Venp_id`)
    REFERENCES `estetica`.`Venta_Producto` (`Venp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estetica`.`Producto_has_Protocolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estetica`.`Producto_has_Protocolo` (
  `Producto_Pro_id` INT NOT NULL,
  `Protocolo_Proto_id` INT NOT NULL,
  INDEX `fk_Producto_has_Protocolo_Protocolo1_idx` (`Protocolo_Proto_id` ASC),
  INDEX `fk_Producto_has_Protocolo_Producto1_idx` (`Producto_Pro_id` ASC),
  CONSTRAINT `fk_Producto_has_Protocolo_Producto1`
    FOREIGN KEY (`Producto_Pro_id`)
    REFERENCES `estetica`.`Producto` (`Pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Protocolo_Protocolo1`
    FOREIGN KEY (`Protocolo_Proto_id`)
    REFERENCES `estetica`.`Protocolo` (`Proto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `estetica`.`Cargo`
-- -----------------------------------------------------
Create table Cargo (
	Cargo_id int primary key,
    Cargo_nom varchar(15) );
    
-- -----------------------------------------------------
-- Table `estetica`.`Transaccion`
-- -----------------------------------------------------
 CREATE TABLE `estetica`.`Transaccion` (
  `idTransaccion` INT NOT NULL AUTO_INCREMENT,
  `Tran_monto` INT NOT NULL,
  `Tran_tipo` VARCHAR(10) NULL,
  `Tran_Ven_id` INT NULL,
  `Tran_idCompraProveedor` INT NULL,
  `Tran_estado_inicial` INT NULL,
  `Tran_estado_final` INT NULL,
  PRIMARY KEY (`idTransaccion`),
  INDEX `fk_Tansaccion_Venta_idx` (`Tran_Ven_id` ASC),
  INDEX `fk_Transaccion_CompraProv_idx` (`Tran_idCompraProveedor` ASC),
  CONSTRAINT `fk_Transaccion_Venta`
    FOREIGN KEY (`Tran_Ven_id`)
    REFERENCES `estetica`.`Venta` (`Ven_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaccion_CompraProv`
    FOREIGN KEY (`Tran_idCompraProveedor`)
    REFERENCES `estetica`.`CompraProveedor` (`idCompraProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
   
    
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
